// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.2
// source: server.proto

package shared

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CoreServer_SendMessageToCore_FullMethodName = "/shared.core.coreServer/SendMessageToCore"
	CoreServer_RegisterMe_FullMethodName        = "/shared.core.coreServer/RegisterMe"
)

// CoreServerClient is the client API for CoreServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CoreServerClient interface {
	SendMessageToCore(ctx context.Context, in *MessageCore, opts ...grpc.CallOption) (*EchoCore, error)
	RegisterMe(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
}

type coreServerClient struct {
	cc grpc.ClientConnInterface
}

func NewCoreServerClient(cc grpc.ClientConnInterface) CoreServerClient {
	return &coreServerClient{cc}
}

func (c *coreServerClient) SendMessageToCore(ctx context.Context, in *MessageCore, opts ...grpc.CallOption) (*EchoCore, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EchoCore)
	err := c.cc.Invoke(ctx, CoreServer_SendMessageToCore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServerClient) RegisterMe(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, CoreServer_RegisterMe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoreServerServer is the server API for CoreServer service.
// All implementations must embed UnimplementedCoreServerServer
// for forward compatibility.
type CoreServerServer interface {
	SendMessageToCore(context.Context, *MessageCore) (*EchoCore, error)
	RegisterMe(context.Context, *RegisterRequest) (*RegisterResponse, error)
	mustEmbedUnimplementedCoreServerServer()
}

// UnimplementedCoreServerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCoreServerServer struct{}

func (UnimplementedCoreServerServer) SendMessageToCore(context.Context, *MessageCore) (*EchoCore, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMessageToCore not implemented")
}
func (UnimplementedCoreServerServer) RegisterMe(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterMe not implemented")
}
func (UnimplementedCoreServerServer) mustEmbedUnimplementedCoreServerServer() {}
func (UnimplementedCoreServerServer) testEmbeddedByValue()                    {}

// UnsafeCoreServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoreServerServer will
// result in compilation errors.
type UnsafeCoreServerServer interface {
	mustEmbedUnimplementedCoreServerServer()
}

func RegisterCoreServerServer(s grpc.ServiceRegistrar, srv CoreServerServer) {
	// If the following call pancis, it indicates UnimplementedCoreServerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CoreServer_ServiceDesc, srv)
}

func _CoreServer_SendMessageToCore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageCore)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServerServer).SendMessageToCore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreServer_SendMessageToCore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServerServer).SendMessageToCore(ctx, req.(*MessageCore))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreServer_RegisterMe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServerServer).RegisterMe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreServer_RegisterMe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServerServer).RegisterMe(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CoreServer_ServiceDesc is the grpc.ServiceDesc for CoreServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CoreServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "shared.core.coreServer",
	HandlerType: (*CoreServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMessageToCore",
			Handler:    _CoreServer_SendMessageToCore_Handler,
		},
		{
			MethodName: "RegisterMe",
			Handler:    _CoreServer_RegisterMe_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server.proto",
}
